language: java

matrix:
  include:
    - os: linux
      sudo: required
      jdk: openjdk11

git:
  quiet: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

stages:
  - Build

jobs:
  include:
    - stage: Build
      script: ./gradlew build --info --stacktrace --max-workers=1 --build-cache

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

#deploy:
#  - provider: script
#    script: ./gradlew artifactoryPublish
#    skip_cleanup: true
#    on:
#      repo: Kryszak/gwatlin
#      tags: true
